// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Yotsuba&!",
    url: "https://upload.wikimedia.org/wikipedia/en/0/01/Yotsuba%26-vol1cover-jp.png",
    originalPrice: 29.99,
    salePrice: 14.99,
    rating: 4.5,
  },
  {
    id: 2,
    title: "One Piece",
    url: "https://upload.wikimedia.org/wikipedia/en/a/a3/One_Piece%2C_Volume_1.jpg",
    originalPrice: 29.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Bleach",
    url: "https://upload.wikimedia.org/wikipedia/en/3/3f/Bleach_%28manga%29_1.png",
    originalPrice: 29.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Hunter X Hunter",
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Hunter_%C3%97_Hunter_vol._1.png/220px-Hunter_%C3%97_Hunter_vol._1.png",
    originalPrice: 29.99,
    salePrice: 19.99,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Naruto",
    url: "https://upload.wikimedia.org/wikipedia/en/9/94/NarutoCoverTankobon1.jpg",
    originalPrice: 29.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Dragon Ball",
    url: "https://upload.wikimedia.org/wikipedia/en/c/c9/DB_Tank%C5%8Dbon.png",
    originalPrice: 29.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 7,
    title: "Slam Dunk",
    url: "https://upload.wikimedia.org/wikipedia/en/f/f7/Slam_Dunk_%28manga%29_1.png",
    originalPrice: 29.99,
    salePrice: 24.99,
    rating: 5,
  },
  {
    id: 8,
    title: "Prince of Tennis",
    url: "https://upload.wikimedia.org/wikipedia/en/1/11/The_Prince_of_Tennis_DVD_box_set_1.jpg",
    originalPrice: 19.99,
    salePrice: 14.99,
    rating: 4,
  },
  {
    id: 9,
    title: "Demon Slayer",
    url: "https://upload.wikimedia.org/wikipedia/en/0/09/Demon_Slayer_-_Kimetsu_no_Yaiba%2C_volume_1.jpg",
    originalPrice: 24.99,
    salePrice: 19.99,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Attack On Titan",
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/Shingeki_no_Kyojin_manga_volume_1.jpg/220px-Shingeki_no_Kyojin_manga_volume_1.jpg",
    originalPrice: 29.99,
    salePrice: 24.99,
    rating: 5,
  },
  {
    id: 11,
    title: "A Silent Voice",
    url: "https://upload.wikimedia.org/wikipedia/en/6/6c/Koe_no_Katachi%2C_Volume_1.jpg",
    originalPrice: 24.99,
    salePrice: 14.99,
    rating: 5,
  },
  {
    id: 12,
    title: "Mob Psycho",
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4b/Mob_Psycho_100_manga_vol_1.jpg/220px-Mob_Psycho_100_manga_vol_1.jpg",
    originalPrice: 24.99,
    salePrice: 14.99,
    rating: 4.5,
  },
];