// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    url: "https://coderslegacy.com/wp-content/uploads/2022/07/1_P7pTGa-PMfCq1VWuNJioig.png",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Atomic Habits",
    url: "https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    url: "https://images-na.ssl-images-amazon.com/images/I/61eUu0OPzgL.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Deep Work",
    url: "https://images-na.ssl-images-amazon.com/images/I/71yA4+MC46L.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The 10X Rule",
    url: "https://images-na.ssl-images-amazon.com/images/I/71hjq42hvGL.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    url: "https://images-na.ssl-images-amazon.com/images/I/81Ibak0tCqL.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    url: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    url: "https://m.media-amazon.com/images/I/41aJnFuCBWL.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    url: "https://media.s-bol.com/OZrG88y2gE0p/mOyPMNO/550x830.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    url: "https://i.pinimg.com/originals/d7/24/a5/d724a5a4ad06c437e5bf7d0d277be1b2.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    url: "https://m.media-amazon.com/images/I/41FYFMn7lZL._AC_SY780_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Mastery",
    url: "https://upload.wikimedia.org/wikipedia/en/9/98/Mastery_Cover.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];